version: 2
updates:
  - package-ecosystem: "pip"  # Para dependências Python (requirements.txt, setup.py, etc.)
    directory: "/"            # Diretório raiz do projeto
    schedule:
      interval: "daily"       # Verifica atualizações diariamente
    open-pull-requests-limit: 10  # Limita PRs abertos para evitar sobrecarga:cite[3]:cite[6]

  - package-ecosystem: "github-actions"  # Atualiza GitHub Actions
    directory: "/"
    schedule:
      interval: "weekly"
