name: Dependabot Auto-Merge
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    # Aplica apenas a PRs do Dependabot e que passaram nos testes
    if: |
      github.actor == 'dependabot[bot]' &&
      github.event.pull_request.mergeable == true &&
      github.event.pull_request.review_comments == 0  # Ignora PRs com comentários de revisão

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.AUTO_MERGE_TOKEN }}"

      - name: Habilitar Auto-Merge
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          # Aprova o PR se necessário e faz merge automático
          gh pr review $PR_NUMBER --approve
          gh pr merge $PR_NUMBER --auto --merge --body "Automerged by Dependabot workflow"