name: Dependabot Auto-Merge
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && contains(github.event.pull_request.title, 'Bump') }}
    steps:
      - name: Auto merge Dependabot PR
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN }}
        run: gh pr merge --auto --merge "$PR_URL"
