name: Dependabot Auto-Merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: |
      github.actor == 'dependabot[bot]' &&
      github.event.pull_request.title contains 'Bump'  # Filtra PRs do Dependabot:cite[4]:cite[7]
      
    steps:
      - name: Habilitar Auto-Merge
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN }}  # Token com permissões para merge
        run: |
          gh pr merge --auto --merge "$PR_URL"